// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbAxtDF4CG1xhsBCrjDLKMYKOJbEW-Mw',
    appId: '1:747727448669:web:ce13c82c0dade7b73a3bb4',
    messagingSenderId: '747727448669',
    projectId: 'done-app-b0985',
    authDomain: 'done-app-b0985.firebaseapp.com',
    storageBucket: 'done-app-b0985.appspot.com',
    measurementId: 'G-EGSC39D607',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkadJbKi_cWPgTuwkc9ZXNwloDVdgD8yw',
    appId: '1:747727448669:android:fe325c870994994f3a3bb4',
    messagingSenderId: '747727448669',
    projectId: 'done-app-b0985',
    storageBucket: 'done-app-b0985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX03iMShuKnVw_9AB0iB0DRWwgO2fiy4w',
    appId: '1:747727448669:ios:4a933019dfe3a1053a3bb4',
    messagingSenderId: '747727448669',
    projectId: 'done-app-b0985',
    storageBucket: 'done-app-b0985.appspot.com',
    iosBundleId: 'com.cefet.doneapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX03iMShuKnVw_9AB0iB0DRWwgO2fiy4w',
    appId: '1:747727448669:ios:58378003c3e09d473a3bb4',
    messagingSenderId: '747727448669',
    projectId: 'done-app-b0985',
    storageBucket: 'done-app-b0985.appspot.com',
    iosBundleId: 'com.cefet.doneapp.RunnerTests',
  );
}
